[default]
vo=gpu
gpu-api=opengl
hwdec=auto
profile=gpu-hq
gpu-context=wayland
script-opts=ytdl_hook-ytdl_path=yt-dlp

[mpvpaper]
vo=libmpv
gpu-api=opengl
hwdec=auto
gpu-context=wayland
softvol=no
aid=no
hr-seek=no
sid=no
sub-auto=no
hr-seek=no
vd-lavc-fast
vd-lavc-skiploopfilter=all
