[default]
drm-device=/dev/dri/renderD128
vo=gpu
gpu-api=opengl
hwdec=nvdec
profile=gpu-hq
gpu-context=wayland

[mpvpaper]
drm-device=/dev/dri/renderD128
vo=libmpv
gpu-api=vulkan
hwdec=auto
gpu-context=wayland
aid=no
hr-seek=no
sid=no
sub-auto=no
hr-seek=no
vd-lavc-fast
vd-lavc-skiploopfilter=all
loop