{
  inputs,
  lib,
  config,
  pkgs,
  ...
}: {
  # add the home manager module
  imports = [inputs.ags.homeManagerModules.default];

  home.packages = with pkgs; [
    # Python
    (python311.withPackages (p:
      with p; [
        materialyoucolor
        setproctitle
        material-color-utilities
        pywal
        pywayland
        pygobject3
      ]))

    # MicroTex Deps
    tinyxml-2
    gtkmm3
    gtksourceviewmm
    cairomm

    # Gnome Stuff
    gnome-control-center
    gnome-bluetooth
    gnome-shell
    blueberry

    # GTK
    webp-pixbuf-loader
    gtk-layer-shell
    gtk3
    gtksourceview3
    upower
    gobject-introspection

    # AGS and Hyprland dependencies.
    glib
    material-symbols
    fuzzel
    ripgrep
    dart-sass
    sassc
    axel
    hyprpicker
    gammastep
    bc
    gradience
    playerctl
    yad
    ydotool
    xdg-user-dirs
  ];

  programs.ags = {
    enable = true;

    # null or path, leave as null if you don't want hm to manage the config
    configDir = null;

    # additional packages to add to gjs's runtime
    extraPackages = with pkgs; [
      # pkgs2311.gtksourceview
      gtksourceview
      webkitgtk
      accountsservice
    ];
  };

  # For the zsh implementing terminal colors
  # that's autogenerated by changing wallpaper
  programs.zsh.initExtra = ''
    if test -f ~/.cache/ags/user/generated/terminal/sequences.txt; then
      cat ~/.cache/ags/user/generated/terminal/sequences.txt
    fi
  '';
}
