# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  helium = {
    pname = "helium";
    version = "0.7.10.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.7.10.1/helium-0.7.10.1-x86_64.AppImage";
      sha256 = "sha256-11xSlHIqmyyVwjjwt5FmLhp72P3m07PppOo7a9DbTcE=";
    };
  };
  materialyoucolor = {
    pname = "materialyoucolor";
    version = "2.0.10";
    src = fetchurl {
      url = "https://pypi.org/packages/source/m/materialyoucolor/materialyoucolor-2.0.10.tar.gz";
      sha256 = "sha256-MbTUB7mk/UtUswVZsNAxP21tofnRm3VUbtZdpSZx6nY=";
    };
  };
  my-custom-fonts = {
    pname = "my-custom-fonts";
    version = "1.0";
    src = fetchurl {
      url = "https://github.com/eekrain/dotfiles/releases/download/1.0/my_custom_fonts.tar.xz";
      sha256 = "sha256-J2xoO1hAnKkbRAMUKKuDJ85DBGRCHSIeDIiDD1+PSS8=";
    };
  };
  sddm-sugar-candy = {
    pname = "sddm-sugar-candy";
    version = "a1fae5159c8f7e44f0d8de124b14bae583edb5b8";
    src = fetchFromGitHub {
      owner = "eekrain";
      repo = "sddm-sugar-candy";
      rev = "a1fae5159c8f7e44f0d8de124b14bae583edb5b8";
      fetchSubmodules = false;
      sha256 = "sha256-p2d7I0UBP63baW/q9MexYJQcqSmZ0L5rkwK3n66gmqM=";
    };
    date = "2020-02-01";
  };
  waybar-mpris = {
    pname = "waybar-mpris";
    version = "485ec0ec0af80a0d63c10e94aebfc59b16aab46b";
    src = fetchgit {
      url = "https://git.hrfee.pw/hrfee/waybar-mpris.git";
      rev = "485ec0ec0af80a0d63c10e94aebfc59b16aab46b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-BjLxWnDNsR2ZnNklNiKzi1DeoPpaZsRdKbVSwNwYhJ4=";
    };
    date = "2022-01-27";
  };
}
