# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  waybar-mpris = {
    pname = "waybar-mpris";
    version = "485ec0ec0af80a0d63c10e94aebfc59b16aab46b";
    src = fetchgit {
      url = "https://git.hrfee.pw/hrfee/waybar-mpris.git";
      rev = "485ec0ec0af80a0d63c10e94aebfc59b16aab46b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-BjLxWnDNsR2ZnNklNiKzi1DeoPpaZsRdKbVSwNwYhJ4=";
    };
    date = "2022-01-27";
  };
}
